from typing import Any


ALTERNATIVES: dict[str, list[dict]] = {
    "Linear Search": [
        {
            "algorithm": "Binary Search",
            "time_complexity": "O(log n)",
            "space_complexity": "O(1)",
            "explanation": "If the array is sorted, binary search divides the search space in half each iteration.",
            "why_faster": "Eliminates half the remaining elements per comparison instead of checking each one sequentially.",
            "additional_memory": "None required (iterative implementation uses only a few variables).",
            "when_current_better": "When the array is unsorted or very small (n < 20).",
            "when_alternative_better": "When the array is sorted and large, binary search is exponentially faster.",
        },
        {
            "algorithm": "Hash Map Lookup",
            "time_complexity": "O(1) average",
            "space_complexity": "O(n)",
            "explanation": "Build a hash map from values to indices, then check if target exists.",
            "why_faster": "Hash map provides O(1) average case lookup instead of O(n) scanning.",
            "additional_memory": "Requires O(n) extra space for the hash map.",
            "when_current_better": "When memory is constrained or you only need to search once.",
            "when_alternative_better": "When you need multiple lookups on the same dataset.",
        },
    ],
    "Binary Search": [
        {
            "algorithm": "Linear Search",
            "time_complexity": "O(n)",
            "space_complexity": "O(1)",
            "explanation": "Sequentially checks each element until the target is found.",
            "why_faster": "Binary search is faster — it's O(log n) vs O(n).",
            "additional_memory": "None.",
            "when_current_better": "Always better than linear search for sorted arrays.",
            "when_alternative_better": "When the array is unsorted or very small.",
        },
    ],
    "Bubble Sort": [
        {
            "algorithm": "Insertion Sort",
            "time_complexity": "O(n²) worst, O(n) best",
            "space_complexity": "O(1)",
            "explanation": "Builds sorted array incrementally by inserting each element into its correct position.",
            "why_faster": "Insertion sort can be O(n) for nearly sorted data, while bubble sort is always O(n²).",
            "additional_memory": "None.",
            "when_current_better": "Bubble sort teaches the concept of swapping but is rarely used in practice.",
            "when_alternative_better": "For small or nearly sorted datasets, insertion sort performs much better.",
        },
        {
            "algorithm": "Merge Sort",
            "time_complexity": "O(n log n)",
            "space_complexity": "O(n)",
            "explanation": "Recursively divides array into halves, sorts each, then merges them back.",
            "why_faster": "O(n log n) is significantly faster than O(n²) for large arrays.",
            "additional_memory": "Requires O(n) extra space for merging.",
            "when_current_better": "When simplicity is preferred over performance (teaching purposes).",
            "when_alternative_better": "For large arrays where O(n log n) performance matters.",
        },
        {
            "algorithm": "Quick Sort",
            "time_complexity": "O(n log n) average, O(n²) worst",
            "space_complexity": "O(log n)",
            "explanation": "Picks a pivot and partitions the array around it, then recursively sorts subarrays.",
            "why_faster": "O(n log n) average case with low constant factors.",
            "additional_memory": "O(log n) for recursion stack.",
            "when_current_better": "When code simplicity is the main concern.",
            "when_alternative_better": "Quick sort is generally the fastest in practice for large random arrays.",
        },
    ],
    "Selection Sort": [
        {
            "algorithm": "Insertion Sort",
            "time_complexity": "O(n²) worst, O(n) best",
            "space_complexity": "O(1)",
            "explanation": "Builds sorted array incrementally; performs especially well on nearly sorted data.",
            "why_faster": "Insertion sort adapts to existing order, making it O(n) on nearly sorted data.",
            "additional_memory": "None.",
            "when_current_better": "Selection sort makes fewer swaps (O(n)) than insertion sort.",
            "when_alternative_better": "Insertion sorts in-place with fewer comparisons on average.",
        },
    ],
    "Insertion Sort": [
        {
            "algorithm": "Merge Sort",
            "time_complexity": "O(n log n)",
            "space_complexity": "O(n)",
            "explanation": "Divide-and-conquer sorting with guaranteed O(n log n) performance.",
            "why_faster": "O(n log n) is much faster than O(n²) for large arrays.",
            "additional_memory": "O(n) for temporary arrays during merge.",
            "when_current_better": "For very small arrays (n < 15) or nearly sorted data.",
            "when_alternative_better": "For large arrays where consistent performance matters.",
        },
    ],
    "Merge Sort": [
        {
            "algorithm": "Quick Sort",
            "time_complexity": "O(n log n) average",
            "space_complexity": "O(log n)",
            "explanation": "In-place sorting with good average performance.",
            "why_faster": "Quick sort typically has lower constant factors and works in-place.",
            "additional_memory": "O(log n) recursion stack only.",
            "when_current_better": "When stable sorting or guaranteed O(n log n) is required.",
            "when_alternative_better": "When memory is limited and average-case speed is prioritized.",
        },
    ],
    "Quick Sort": [
        {
            "algorithm": "Merge Sort",
            "time_complexity": "O(n log n)",
            "space_complexity": "O(n)",
            "explanation": "Stable divide-and-conquer sorting with guaranteed O(n log n).",
            "why_faster": "Merge sort guarantees O(n log n) even in worst case, unlike quick sort's O(n²).",
            "additional_memory": "O(n) for auxiliary arrays.",
            "when_current_better": "When average performance matters and worst case is unlikely.",
            "when_alternative_better": "When guaranteed performance and stability are needed.",
        },
    ],
    "Two Pointers": [
        {
            "algorithm": "Hash Map",
            "time_complexity": "O(n)",
            "space_complexity": "O(n)",
            "explanation": "Store visited values in a hash map for O(1) lookup instead of scanning.",
            "why_faster": "Hash maps provide O(1) lookup, useful when the problem requires pairing elements.",
            "additional_memory": "O(n) extra space for the hash map.",
            "when_current_better": "When the array is sorted and you want O(1) space.",
            "when_alternative_better": "When the array is unsorted and you need O(n) time without sorting.",
        },
    ],
    "Sliding Window": [
        {
            "algorithm": "Prefix Sum",
            "time_complexity": "O(n)",
            "space_complexity": "O(n)",
            "explanation": "Precompute cumulative sums to answer range sum queries in O(1).",
            "why_faster": "Prefix sums allow O(1) range queries after O(n) preprocessing.",
            "additional_memory": "O(n) for the prefix sum array.",
            "when_current_better": "When you need to track contiguous subarrays dynamically.",
            "when_alternative_better": "When you need many range sum queries on a static array.",
        },
        {
            "algorithm": "Brute Force",
            "time_complexity": "O(n×k)",
            "space_complexity": "O(1)",
            "explanation": "Check every possible window/subarray from scratch.",
            "why_faster": "Sliding window is already optimal — O(n) vs O(n×k).",
            "additional_memory": "None.",
            "when_current_better": "Sliding window is always better than brute force for window-based problems.",
            "when_alternative_better": "Only when the problem does not have overlapping subarray structure.",
        },
    ],
    "Prefix Sum": [
        {
            "algorithm": "Fenwick Tree / BIT",
            "time_complexity": "O(log n) per query",
            "space_complexity": "O(n)",
            "explanation": "Tree structure supporting point updates and prefix queries in O(log n).",
            "why_faster": "Fenwick tree allows updates, which prefix sum does not.",
            "additional_memory": "O(n) for the tree array.",
            "when_current_better": "When the array is static with no updates needed.",
            "when_alternative_better": "When the array changes frequently and you need range sum queries.",
        },
    ],
    "Hashing / Hash Map": [
        {
            "algorithm": "Sorting + Two Pointers",
            "time_complexity": "O(n log n)",
            "space_complexity": "O(1)",
            "explanation": "Sort the array and use two pointers to find pairs efficiently.",
            "why_faster": "Uses O(1) extra space instead of O(n) for the hash map.",
            "additional_memory": "None (in-place sorting).",
            "when_current_better": "When O(n) space is acceptable and you need O(n) time.",
            "when_alternative_better": "When memory is constrained and you can afford O(n log n) time.",
        },
    ],
    "Stack": [
        {
            "algorithm": "Array / List",
            "time_complexity": "O(1) per operation",
            "space_complexity": "O(n)",
            "explanation": "Use array with index pointer to simulate stack behavior.",
            "why_faster": "Array-based stack can be faster due to CPU cache locality.",
            "additional_memory": "Same O(n).",
            "when_current_better": "Stack is the standard choice for LIFO operations.",
            "when_alternative_better": "When you need indexed access to stack elements.",
        },
    ],
    "Monotonic Stack": [
        {
            "algorithm": "Brute Force",
            "time_complexity": "O(n²)",
            "space_complexity": "O(1)",
            "explanation": "For each element, scan the rest of the array to find the next smaller/larger element.",
            "why_faster": "Monotonic stack reduces O(n²) to O(n) by maintaining useful ordering.",
            "additional_memory": "O(n) for the stack.",
            "when_current_better": "Monotonic stack is always the better choice for next-greater-element problems.",
            "when_alternative_better": "Never for this class of problems.",
        },
    ],
    "Queue": [
        {
            "algorithm": "Deque (Double-Ended Queue)",
            "time_complexity": "O(1) per operation",
            "space_complexity": "O(n)",
            "explanation": "Use collections.deque for O(1) operations on both ends.",
            "why_faster": "Deque supports O(1) operations from both ends vs queue's single-ended ops.",
            "additional_memory": "Same O(n).",
            "when_current_better": "When only FIFO operations are needed.",
            "when_alternative_better": "When you need to add/remove from both ends efficiently.",
        },
    ],
    "Priority Queue / Heap": [
        {
            "algorithm": "Sorting",
            "time_complexity": "O(n log n)",
            "space_complexity": "O(1)",
            "explanation": "Sort the array once and pick the kth element directly.",
            "why_faster": "For extracting all elements, both are O(n log n). For k smallest, heap is O(n log k).",
            "additional_memory": "Sorting may be in-place (O(1)), heap uses O(k).",
            "when_current_better": "For dynamic insertions with extraction of minimum/maximum.",
            "when_alternative_better": "When you only need to query once and the data is static.",
        },
    ],
    "Recursion": [
        {
            "algorithm": "Iteration (Dynamic Programming)",
            "time_complexity": "O(n)",
            "space_complexity": "O(1)",
            "explanation": "Use loops and tabulation instead of recursive function calls.",
            "why_faster": "Avoids function call overhead and stack overflow risk.",
            "additional_memory": "O(1) vs O(n) stack space for recursion.",
            "when_current_better": "When the recursive solution is more intuitive and stack depth is low.",
            "when_alternative_better": "For deep recursion or performance-critical code.",
        },
        {
            "algorithm": "Memoization (Top-Down DP)",
            "time_complexity": "O(n)",
            "space_complexity": "O(n)",
            "explanation": "Cache recursive results to avoid redundant calculations.",
            "why_faster": "Reduces exponential time to polynomial by storing computed values.",
            "additional_memory": "O(n) for the cache.",
            "when_current_better": "For simple recursion with no overlapping subproblems.",
            "when_alternative_better": "When recursive function has overlapping subproblems (e.g., Fibonacci).",
        },
    ],
    "Backtracking": [
        {
            "algorithm": "Dynamic Programming",
            "time_complexity": "O(poly(n))",
            "space_complexity": "O(poly(n))",
            "explanation": "Store and reuse results for overlapping subproblems.",
            "why_faster": "DP avoids re-exploring the same states, reducing exponential to polynomial time.",
            "additional_memory": "DP table or memo cache.",
            "when_current_better": "When the search space is small or the solution requires exploring all possibilities.",
            "when_alternative_better": "When subproblems overlap and optimal substructure exists.",
        },
        {
            "algorithm": "Greedy Algorithm",
            "time_complexity": "O(n)",
            "space_complexity": "O(1)",
            "explanation": "Make the locally optimal choice at each step without exploring alternatives.",
            "why_faster": "Greedy runs in O(n) without branching.",
            "additional_memory": "None.",
            "when_current_better": "When a greedy solution does not exist or fails for the problem.",
            "when_alternative_better": "When the problem has the greedy choice property (e.g., coin change with canonical coins).",
        },
    ],
    "Divide and Conquer": [
        {
            "algorithm": "Dynamic Programming",
            "time_complexity": "O(poly(n))",
            "space_complexity": "O(poly(n))",
            "explanation": "Break into subproblems that overlap and cache results.",
            "why_faster": "DP handles overlapping subproblems that divide-and-conquer re-solves.",
            "additional_memory": "DP table.",
            "when_current_better": "When subproblems are independent.",
            "when_alternative_better": "When subproblems overlap significantly.",
        },
    ],
    "Greedy Algorithm": [
        {
            "algorithm": "Dynamic Programming",
            "time_complexity": "O(poly(n))",
            "space_complexity": "O(poly(n))",
            "explanation": "Consider all possibilities and choose the optimal combination using stored results.",
            "why_faster": "Greedy is faster when applicable (O(n) vs O(n²) or more).",
            "additional_memory": "DP requires more memory.",
            "when_current_better": "When the greedy choice property holds, greedy is simpler and faster.",
            "when_alternative_better": "When greedy fails to find the global optimum.",
        },
    ],
    "Dynamic Programming": [
        {
            "algorithm": "Greedy Algorithm",
            "time_complexity": "O(n)",
            "space_complexity": "O(1)",
            "explanation": "Take locally optimal steps without exploring the full state space.",
            "why_faster": "Greedy avoids DP table construction and state enumeration.",
            "additional_memory": "Minimal.",
            "when_current_better": "When greedy fails to find the optimal solution.",
            "when_alternative_better": "When the problem has optimal substructure with greedy choice property.",
        },
        {
            "algorithm": "Memoization (Top-Down DP)",
            "time_complexity": "O(poly(n))",
            "space_complexity": "O(poly(n))",
            "explanation": "Recursive approach with caching instead of iterative tabulation.",
            "why_faster": "Top-down only computes states that are actually needed.",
            "additional_memory": "Similar to bottom-up DP.",
            "when_current_better": "Bottom-up DP avoids recursion overhead and stack limits.",
            "when_alternative_better": "When the state space is sparse or not all states are reachable.",
        },
    ],
    "Breadth-First Search": [
        {
            "algorithm": "Depth-First Search",
            "time_complexity": "O(V + E)",
            "space_complexity": "O(V)",
            "explanation": "Recursively explore each branch as deeply as possible before backtracking.",
            "why_faster": "DFS uses less memory (stack vs queue) and can find solutions faster in deep graphs.",
            "additional_memory": "O(h) where h is graph depth (vs O(w) width for BFS).",
            "when_current_better": "When shortest path is needed (BFS guarantees shortest path in unweighted graphs).",
            "when_alternative_better": "When memory is constrained or you need to explore deep paths.",
        },
        {
            "algorithm": "Dijkstra's Algorithm",
            "time_complexity": "O((V + E) log V)",
            "space_complexity": "O(V)",
            "explanation": "Extension of BFS that handles weighted edges using a priority queue.",
            "why_faster": "BFS is faster for unweighted graphs (O(V+E) vs O((V+E)log V)).",
            "additional_memory": "Priority queue adds some overhead.",
            "when_current_better": "For unweighted graphs, BFS is simpler and faster.",
            "when_alternative_better": "When edges have weights and shortest weighted path is needed.",
        },
    ],
    "Depth-First Search": [
        {
            "algorithm": "Breadth-First Search",
            "time_complexity": "O(V + E)",
            "space_complexity": "O(V)",
            "explanation": "Explore level by level using a queue.",
            "why_faster": "BFS finds shortest path in unweighted graphs.",
            "additional_memory": "Queue may use more memory for wide graphs.",
            "when_current_better": "When memory is limited or you need to explore deep paths.",
            "when_alternative_better": "When shortest path in unweighted graph or level-order traversal is needed.",
        },
    ],
    "Topological Sort": [
        {
            "algorithm": "DFS-based Topological Sort",
            "time_complexity": "O(V + E)",
            "space_complexity": "O(V)",
            "explanation": "Use DFS with a stack to record finishing times for reverse topological order.",
            "why_faster": "Same complexity; choice depends on preference.",
            "additional_memory": "Same.",
            "when_current_better": "Kahn\'s algorithm (BFS) is intuitive with indegree tracking.",
            "when_alternative_better": "DFS approach is simpler to implement recursively.",
        },
    ],
    "Dijkstra's Algorithm": [
        {
            "algorithm": "Bellman-Ford Algorithm",
            "time_complexity": "O(V × E)",
            "space_complexity": "O(V)",
            "explanation": "Relaxes all edges V-1 times to handle negative edge weights.",
            "why_faster": "Dijkstra is faster (O((V+E)log V) vs O(VE)).",
            "additional_memory": "Same O(V).",
            "when_current_better": "For graphs with non-negative weights.",
            "when_alternative_better": "When negative edge weights are present.",
        },
        {
            "algorithm": "A* Search",
            "time_complexity": "O(E) in practice",
            "space_complexity": "O(V)",
            "explanation": "Extends Dijkstra with a heuristic to guide search toward the goal.",
            "why_faster": "A* explores fewer nodes when a good heuristic is available.",
            "additional_memory": "Same O(V) with heuristic storage.",
            "when_current_better": "When no good heuristic exists or all nodes are equally likely.",
            "when_alternative_better": "For pathfinding in grid maps or graphs with spatial information.",
        },
    ],
    "Bellman-Ford Algorithm": [
        {
            "algorithm": "Dijkstra's Algorithm",
            "time_complexity": "O((V + E) log V)",
            "space_complexity": "O(V)",
            "explanation": "Faster algorithm for graphs with non-negative edge weights.",
            "why_faster": "Dijkstra is significantly faster for non-negative graphs.",
            "additional_memory": "Same O(V).",
            "when_current_better": "When negative edges exist or negative cycle detection is needed.",
            "when_alternative_better": "For graphs where all edge weights are non-negative.",
        },
    ],
    "Union-Find": [
        {
            "algorithm": "DFS / BFS for Connectivity",
            "time_complexity": "O(V + E) per query",
            "space_complexity": "O(V + E)",
            "explanation": "Use DFS/BFS from one node to check if another is reachable.",
            "why_faster": "Union-Find with path compression is nearly O(1) per operation.",
            "additional_memory": "Union-find uses O(V) vs O(V+E) for graph traversal.",
            "when_current_better": "For dynamic connectivity with many union/find operations.",
            "when_alternative_better": "For single-use connectivity checks in static graphs.",
        },
    ],
    "Trie": [
        {
            "algorithm": "Hash Map of Prefixes",
            "time_complexity": "O(k) per operation",
            "space_complexity": "O(n×k)",
            "explanation": "Store all prefixes directly in a hash map instead of a tree structure.",
            "why_faster": "Hash map has O(1) lookup for exact match vs O(k) trie traversal.",
            "additional_memory": "May use more memory for storing all prefixes.",
            "when_current_better": "For prefix matching (autocomplete, spell check).",
            "when_alternative_better": "For exact string lookup only.",
        },
    ],
    "Bit Manipulation": [
        {
            "algorithm": "Array / Hash Map Counting",
            "time_complexity": "O(n)",
            "space_complexity": "O(n)",
            "explanation": "Count occurrences using an array or hash map instead of bitwise tricks.",
            "why_faster": "Bit manipulation is faster and uses less memory.",
            "additional_memory": "Bit manipulation uses O(1) vs O(n) for counting arrays.",
            "when_current_better": "Bit manipulation is almost always better when applicable.",
            "when_alternative_better": "When code readability matters more than performance.",
        },
    ],
    "Counting Sort": [
        {
            "algorithm": "Built-in Sort / Quick Sort",
            "time_complexity": "O(n log n)",
            "space_complexity": "O(1)",
            "explanation": "Use the standard library sort function.",
            "why_faster": "Counting sort is O(n + k) which is faster when k is small.",
            "additional_memory": "Counting sort needs O(k) extra space.",
            "when_current_better": "When the range of values (k) is not too large.",
            "when_alternative_better": "When the range is large (k >> n) or values are not integers.",
        },
    ],
    "Floyd-Warshall Algorithm": [
        {
            "algorithm": "Dijkstra (repeated for each node)",
            "time_complexity": "O(V × (V+E) × log V)",
            "space_complexity": "O(V)",
            "explanation": "Run Dijkstra from each node to compute all-pairs shortest paths.",
            "why_faster": "Floyd-Warshall is O(V³), Dijkstra per node is O(V×(V+E)log V). For dense graphs, Floyd-Warshall can be faster.",
            "additional_memory": "Floyd-Warshall uses O(V²) for the distance matrix.",
            "when_current_better": "For dense graphs with V ≤ 400.",
            "when_alternative_better": "For sparse graphs, repeated Dijkstra is more efficient.",
        },
    ],
}


def get_alternative_approaches(algorithm: str) -> list[dict]:
    return ALTERNATIVES.get(algorithm, [])


def get_current_approach_complexity(algorithm: str) -> dict:
    complexity_map = {
        "Linear Search": ("O(n)", "O(1)"),
        "Binary Search": ("O(log n)", "O(1)"),
        "Bubble Sort": ("O(n²)", "O(1)"),
        "Selection Sort": ("O(n²)", "O(1)"),
        "Insertion Sort": ("O(n²)", "O(1)"),
        "Merge Sort": ("O(n log n)", "O(n)"),
        "Quick Sort": ("O(n log n)", "O(log n)"),
        "Heap Sort": ("O(n log n)", "O(1)"),
        "Counting Sort": ("O(n + k)", "O(k)"),
        "Two Pointers": ("O(n)", "O(1)"),
        "Sliding Window": ("O(n)", "O(1)"),
        "Prefix Sum": ("O(n)", "O(n)"),
        "Hashing / Hash Map": ("O(n)", "O(n)"),
        "Stack": ("O(1) per op", "O(n)"),
        "Monotonic Stack": ("O(n)", "O(n)"),
        "Queue": ("O(1) per op", "O(n)"),
        "Priority Queue / Heap": ("O(log n) per op", "O(n)"),
        "Recursion": ("O(n)", "O(n)"),
        "Backtracking": ("O(2ⁿ)", "O(n)"),
        "Divide and Conquer": ("O(n log n)", "O(log n)"),
        "Greedy Algorithm": ("O(n)", "O(1)"),
        "Dynamic Programming": ("O(poly(n))", "O(poly(n))"),
        "Breadth-First Search": ("O(V + E)", "O(V)"),
        "Depth-First Search": ("O(V + E)", "O(V)"),
        "Topological Sort": ("O(V + E)", "O(V)"),
        "Dijkstra's Algorithm": ("O((V+E) log V)", "O(V)"),
        "Bellman-Ford Algorithm": ("O(V × E)", "O(V)"),
        "Floyd-Warshall Algorithm": ("O(V³)", "O(V²)"),
        "Union-Find": ("O(α(n)) per op", "O(n)"),
        "Trie": ("O(k) per op", "O(n × k)"),
        "Bit Manipulation": ("O(n)", "O(1)"),
    }
    return complexity_map.get(algorithm, ("O(n)", "O(1)"))
