from typing import Any


REFERENCES: dict[str, dict] = {
    "Linear Search": {
        "main_concept": "Sequential Search",
        "pattern": "Iterate through data and compare each element to a target.",
        "prerequisites": ["Arrays", "Loops", "Conditional statements"],
        "similar_problems": ["Find Maximum in Array", "Count Occurrences", "First Occurrence"],
        "related_topics": ["Binary Search", "Hashing", "Two Pointers"],
        "practice_problems": [
            "Find the index of a target element",
            "Count how many times a value appears",
            "Find the first and last occurrence",
        ],
        "pseudocode": "for i from 0 to n-1:\n    if arr[i] == target:\n        return i\nreturn -1",
    },
    "Binary Search": {
        "main_concept": "Divide and Conquer Search",
        "pattern": "Repeatedly divide the search space in half.",
        "prerequisites": ["Arrays", "Sorted data", "Recursion or iteration"],
        "similar_problems": ["Find element in rotated sorted array", "Binary search on answer", "Find peak element"],
        "related_topics": ["Divide and Conquer", "Two Pointers", "Search space optimization"],
        "practice_problems": ["LeetCode 704: Binary Search", "LeetCode 34: Find First and Last Position", "LeetCode 33: Search in Rotated Sorted Array"],
        "pseudocode": "low = 0, high = n-1\nwhile low <= high:\n    mid = (low + high) / 2\n    if arr[mid] == target: return mid\n    if arr[mid] < target: low = mid + 1\n    else: high = mid - 1\nreturn -1",
    },
    "Bubble Sort": {
        "main_concept": "Comparison-based Sorting",
        "pattern": "Repeatedly swap adjacent elements if they are in wrong order.",
        "prerequisites": ["Arrays", "Nested loops", "Swapping"],
        "similar_problems": ["Selection Sort", "Insertion Sort", "Sorting fundamentals"],
        "related_topics": ["Sorting algorithms", "Time complexity analysis", "Stable sorting"],
        "practice_problems": ["Sort an array", "Sort with early termination optimization"],
        "pseudocode": "for i = 0 to n-1:\n    for j = 0 to n-i-2:\n        if arr[j] > arr[j+1]:\n            swap(arr[j], arr[j+1])",
    },
    "Selection Sort": {
        "main_concept": "Selection-based Sorting",
        "pattern": "Find minimum element and place it at the beginning.",
        "prerequisites": ["Arrays", "Nested loops", "Finding minimum"],
        "similar_problems": ["Bubble Sort", "Insertion Sort", "Stable selection sort"],
        "related_topics": ["In-place sorting", "Unstable vs stable sorts"],
        "practice_problems": ["Sort an array", "Sort using minimum selection"],
        "pseudocode": "for i = 0 to n-1:\n    min_idx = i\n    for j = i+1 to n-1:\n        if arr[j] < arr[min_idx]:\n            min_idx = j\n    swap(arr[i], arr[min_idx])",
    },
    "Insertion Sort": {
        "main_concept": "Incremental Insertion",
        "pattern": "Build sorted array by inserting elements one by one.",
        "prerequisites": ["Arrays", "Loops", "Shifting elements"],
        "similar_problems": ["Bubble Sort", "Selection Sort", "Shell Sort"],
        "related_topics": ["Adaptive sorting", "Online algorithms", "Nearly sorted data"],
        "practice_problems": ["Sort an array", "Sort while reading input (online sort)"],
        "pseudocode": "for i = 1 to n-1:\n    key = arr[i]\n    j = i-1\n    while j >= 0 and arr[j] > key:\n        arr[j+1] = arr[j]\n        j = j-1\n    arr[j+1] = key",
    },
    "Merge Sort": {
        "main_concept": "Divide and Conquer Sorting",
        "pattern": "Recursively divide, sort, and merge halves.",
        "prerequisites": ["Recursion", "Arrays", "Merge operation"],
        "similar_problems": ["Quick Sort", "Count inversions", "External sorting"],
        "related_topics": ["Divide and Conquer", "Stable sorting", "Parallel sorting"],
        "practice_problems": ["LeetCode 912: Sort an Array", "Count inversions in array", "Merge k sorted lists"],
        "pseudocode": "if n > 1:\n    mid = n / 2\n    left = arr[0:mid]\n    right = arr[mid:n]\n    merge_sort(left)\n    merge_sort(right)\n    merge(left, right, arr)",
    },
    "Quick Sort": {
        "main_concept": "Partition-based Sorting",
        "pattern": "Choose pivot, partition, recursively sort subarrays.",
        "prerequisites": ["Recursion", "Arrays", "Partitioning"],
        "similar_problems": ["Merge Sort", "Quick Select", "Dutch national flag problem"],
        "related_topics": ["In-place sorting", "Randomized algorithms", "Selection algorithms"],
        "practice_problems": ["LeetCode 912: Sort an Array", "LeetCode 215: Kth Largest Element", "Dutch flag partitioning"],
        "pseudocode": "if low < high:\n    pivot = partition(arr, low, high)\n    quick_sort(arr, low, pivot-1)\n    quick_sort(arr, pivot+1, high)",
    },
    "Heap Sort": {
        "main_concept": "Heap-based Sorting",
        "pattern": "Build heap, repeatedly extract maximum.",
        "prerequisites": ["Heap data structure", "Arrays", "Sift-up/sift-down"],
        "similar_problems": ["Priority Queue", "Merge K Sorted", "Top K Elements"],
        "related_topics": ["Heap", "Priority Queue", "Selection algorithms"],
        "practice_problems": ["LeetCode 912: Sort an Array", "Sort using heap", "Merge k sorted arrays"],
        "pseudocode": "build_max_heap(arr)\nfor i = n-1 to 1:\n    swap(arr[0], arr[i])\n    heap_size = heap_size - 1\n    heapify(arr, 0)",
    },
    "Two Pointers": {
        "main_concept": "Two-Pointer Technique",
        "pattern": "Use two pointers to traverse data from different positions.",
        "prerequisites": ["Arrays", "Sorted data concept", "While loops"],
        "similar_problems": ["Two Sum in sorted array", "Remove duplicates", "Container with most water"],
        "related_topics": ["Sliding Window", "Binary Search", "Three Pointers"],
        "practice_problems": ["LeetCode 167: Two Sum II", "LeetCode 11: Container With Most Water", "LeetCode 26: Remove Duplicates"],
        "pseudocode": "left = 0, right = n-1\nwhile left < right:\n    if condition:\n        left += 1\n    else:\n        right -= 1",
    },
    "Sliding Window": {
        "main_concept": "Window-based Traversal",
        "pattern": "Expand and shrink a window to find optimal subarray.",
        "prerequisites": ["Arrays", "Two pointers", "Hash maps"],
        "similar_problems": ["Maximum sum subarray", "Longest substring without repeats", "Minimum window substring"],
        "related_topics": ["Two Pointers", "Prefix Sum", "Queue"],
        "practice_problems": ["LeetCode 3: Longest Substring Without Repeating", "LeetCode 76: Minimum Window Substring", "LeetCode 209: Minimum Size Subarray Sum"],
        "pseudocode": "left = 0\nfor right = 0 to n-1:\n    add arr[right] to window\n    while window is invalid:\n        remove arr[left]\n        left += 1\n    update answer",
    },
    "Prefix Sum": {
        "main_concept": "Cumulative Sum Array",
        "pattern": "Precompute sums for fast range queries.",
        "prerequisites": ["Arrays", "Addition", "Range queries"],
        "similar_problems": ["Range sum query", "Subarray sum equals k", "2D prefix sum"],
        "related_topics": ["Fenwick Tree", "Segment Tree", "Difference Array"],
        "practice_problems": ["LeetCode 303: Range Sum Query", "LeetCode 560: Subarray Sum Equals K", "LeetCode 304: 2D Range Sum Query"],
        "pseudocode": "pref[0] = 0\nfor i = 0 to n-1:\n    pref[i+1] = pref[i] + arr[i]\nsum(l, r) = pref[r+1] - pref[l]",
    },
    "Hashing / Hash Map": {
        "main_concept": "Hash-based Lookup",
        "pattern": "Store values for O(1) average case lookup.",
        "prerequisites": ["Arrays", "Hash functions", "Collision handling"],
        "similar_problems": ["Two Sum", "Contains Duplicate", "Group Anagrams"],
        "related_topics": ["Set", "Hash Table", "Counting"],
        "practice_problems": ["LeetCode 1: Two Sum", "LeetCode 217: Contains Duplicate", "LeetCode 242: Valid Anagram"],
        "pseudocode": "hash_map = {}\nfor each element:\n    if target - element in hash_map:\n        return found\n    hash_map[element] = index",
    },
    "Stack": {
        "main_concept": "LIFO Data Structure",
        "pattern": "Process elements in last-in-first-out order.",
        "prerequisites": ["Arrays", "Function calls", "Push/pop operations"],
        "similar_problems": ["Valid parentheses", "Undo operations", "Expression evaluation"],
        "related_topics": ["Queue", "Monotonic Stack", "Call Stack"],
        "practice_problems": ["LeetCode 20: Valid Parentheses", "LeetCode 155: Min Stack", "LeetCode 394: Decode String"],
        "pseudocode": "stack = []\nstack.append(value)    # push\nvalue = stack.pop()    # pop\ntop = stack[-1]        # peek",
    },
    "Monotonic Stack": {
        "main_concept": "Stack with Ordered Elements",
        "pattern": "Maintain stack where values are monotonically increasing or decreasing.",
        "prerequisites": ["Stack", "Arrays", "Next greater element concept"],
        "similar_problems": ["Next greater element", "Largest rectangle in histogram", "Daily temperatures"],
        "related_topics": ["Stack", "Queue", "Segment Tree"],
        "practice_problems": ["LeetCode 739: Daily Temperatures", "LeetCode 84: Largest Rectangle", "LeetCode 496: Next Greater Element I"],
        "pseudocode": "stack = []\nfor each element:\n    while stack and condition(stack[-1], element):\n        pop and update result\n    push element to stack",
    },
    "Queue": {
        "main_concept": "FIFO Data Structure",
        "pattern": "Process elements in first-in-first-out order.",
        "prerequisites": ["Arrays", "Linked lists", "Enqueue/dequeue"],
        "similar_problems": ["BFS traversal", "Stream processing", "Task scheduling"],
        "related_topics": ["Stack", "Deque", "Circular Buffer"],
        "practice_problems": ["Implement queue with stacks", "Design circular queue", "Recent counter"],
        "pseudocode": "queue = []\nqueue.append(value)     # enqueue\nvalue = queue.pop(0)    # dequeue\nfront = queue[0]        # peek",
    },
    "Priority Queue / Heap": {
        "main_concept": "Heap-based Priority",
        "pattern": "Extract elements based on priority (min/max).",
        "prerequisites": ["Arrays", "Binary tree", "Comparison"],
        "similar_problems": ["Top K elements", "Merge k sorted lists", "Median from stream"],
        "related_topics": ["Heap Sort", "Graph algorithms", "Scheduling"],
        "practice_problems": ["LeetCode 215: Kth Largest", "LeetCode 347: Top K Frequent", "LeetCode 295: Find Median from Stream"],
        "pseudocode": "heap = []\nheappush(heap, value)    # push\nvalue = heappop(heap)    # pop min\npeek = heap[0]           # peek min",
    },
    "Recursion": {
        "main_concept": "Function Self-Call",
        "pattern": "Function calls itself to solve smaller subproblems.",
        "prerequisites": ["Functions", "Call stack", "Base case concept"],
        "similar_problems": ["Tree traversal", "Divide and Conquer", "Backtracking"],
        "related_topics": ["Call Stack", "Dynamic Programming", "Memoization"],
        "practice_problems": ["Factorial", "Fibonacci", "Tree traversals", "Tower of Hanoi"],
        "pseudocode": "def recursive(params):\n    if base_case:\n        return base_value\n    return recursive(smaller_params)",
    },
    "Backtracking": {
        "main_concept": "Systematic Search with Undo",
        "pattern": "Explore decisions recursively, undo when path fails.",
        "prerequisites": ["Recursion", "Pruning", "State space concept"],
        "similar_problems": ["N-Queens", "Sudoku solver", "Generate permutations"],
        "related_topics": ["DFS", "Constraint satisfaction", "Branch and bound"],
        "practice_problems": ["LeetCode 46: Permutations", "LeetCode 51: N-Queens", "LeetCode 79: Word Search"],
        "pseudocode": "def backtrack(path, choices):\n    if goal_reached:\n        save solution\n        return\n    for each choice:\n        make_choice\n        backtrack(path, choices)\n        undo_choice",
    },
    "Divide and Conquer": {
        "main_concept": "Divide-Solve-Combine",
        "pattern": "Break problem into independent subproblems, solve, combine.",
        "prerequisites": ["Recursion", "Merge operation", "Problem decomposition"],
        "similar_problems": ["Merge Sort", "Quick Sort", "Binary Search", "Closest pair"],
        "related_topics": ["Recursion", "Dynamic Programming", "Parallel computing"],
        "practice_problems": ["Merge Sort", "Binary Search", "Maximum subarray (Kadane)"],
        "pseudocode": "def solve(problem):\n    if trivial: return base\n    sub1, sub2 = divide(problem)\n    r1 = solve(sub1)\n    r2 = solve(sub2)\n    return combine(r1, r2)",
    },
    "Greedy Algorithm": {
        "main_concept": "Local Optimal Choice",
        "pattern": "Make the best immediate decision without reconsidering.",
        "prerequisites": ["Sorting", "Priority Queue", "Proof techniques"],
        "similar_problems": ["Activity selection", "Coin change", "Huffman coding"],
        "related_topics": ["Dynamic Programming", "Matroids", "Optimization"],
        "practice_problems": ["LeetCode 55: Jump Game", "LeetCode 122: Best Time to Buy II", "LeetCode 435: Non-overlapping Intervals"],
        "pseudocode": "sort by some criterion\nresult = []\nfor each item:\n    if item fits constraint:\n        add to result",
    },
    "Dynamic Programming": {
        "main_concept": "Optimal Substructure + Memoization",
        "pattern": "Solve subproblems once and reuse results.",
        "prerequisites": ["Recursion", "Arrays", "Problem decomposition"],
        "similar_problems": ["Fibonacci", "Knapsack", "LCS", "LIS", "Coin change"],
        "related_topics": ["Memoization", "Tabulation", "State transition"],
        "practice_problems": ["LeetCode 70: Climbing Stairs", "LeetCode 322: Coin Change", "LeetCode 1143: Longest Common Subsequence"],
        "pseudocode": "dp[0] = base_case\nfor i = 1 to n:\n    dp[i] = best(dp[i-1], dp[i-2], ...)\nreturn dp[n]",
    },
    "Breadth-First Search": {
        "main_concept": "Level-order Graph Traversal",
        "pattern": "Explore neighbors level by level using a queue.",
        "prerequisites": ["Queue", "Graph representation", "Visited tracking"],
        "similar_problems": ["Shortest path in grid", "Word ladder", "Level order tree traversal"],
        "related_topics": ["DFS", "Dijkstra", "Topological Sort"],
        "practice_problems": ["LeetCode 200: Number of Islands", "LeetCode 102: Level Order Traversal", "LeetCode 127: Word Ladder"],
        "pseudocode": "queue = [start]\nvisited = {start}\nwhile queue:\n    node = queue.pop(0)\n    for neighbor of node:\n        if neighbor not in visited:\n            visited.add(neighbor)\n            queue.append(neighbor)",
    },
    "Depth-First Search": {
        "main_concept": "Depth-first Graph Traversal",
        "pattern": "Explore as far as possible along each branch, then backtrack.",
        "prerequisites": ["Recursion/Stack", "Graph representation", "Visited tracking"],
        "similar_problems": ["Connected components", "Path existence", "Topological sort"],
        "related_topics": ["BFS", "Backtracking", "Tree traversals"],
        "practice_problems": ["LeetCode 200: Number of Islands", "LeetCode 207: Course Schedule", "LeetCode 394: Decode String"],
        "pseudocode": "def dfs(node, visited):\n    visited.add(node)\n    for neighbor of node:\n        if neighbor not in visited:\n            dfs(neighbor, visited)",
    },
    "Topological Sort": {
        "main_concept": "Linear Ordering of DAG",
        "pattern": "Order nodes so every edge goes from earlier to later in order.",
        "prerequisites": ["Graph theory", "Queue or Stack", "DAG concept"],
        "similar_problems": ["Course schedule", "Build dependencies", "Task ordering"],
        "related_topics": ["BFS", "DFS", "Kahn's algorithm"],
        "practice_problems": ["LeetCode 207: Course Schedule", "LeetCode 210: Course Schedule II", "Alien Dictionary"],
        "pseudocode": "indegree = count_incoming_edges(graph)\nqueue = nodes with indegree 0\nwhile queue:\n    node = queue.pop()\n    for neighbor of node:\n        indegree[neighbor] -= 1\n        if indegree[neighbor] == 0:\n            queue.append(neighbor)",
    },
    "Dijkstra's Algorithm": {
        "main_concept": "Shortest Path (Non-negative Weights)",
        "pattern": "Use priority queue to relax edges in order of shortest distance.",
        "prerequisites": ["BFS", "Priority Queue", "Graph theory"],
        "similar_problems": ["Network delay time", "Cheapest flights within K stops", "Path with minimum effort"],
        "related_topics": ["Bellman-Ford", "A* Search", "Floyd-Warshall"],
        "practice_problems": ["LeetCode 743: Network Delay Time", "LeetCode 787: Cheapest Flights", "LeetCode 1631: Path With Minimum Effort"],
        "pseudocode": "dist[start] = 0\nheap = [(0, start)]\nwhile heap:\n    d, u = heappop(heap)\n    for v, w in graph[u]:\n        if d + w < dist[v]:\n            dist[v] = d + w\n            heappush(heap, (dist[v], v))",
    },
    "Bellman-Ford Algorithm": {
        "main_concept": "Shortest Path (Negative Weights Allowed)",
        "pattern": "Relax all edges V-1 times to find shortest paths.",
        "prerequisites": ["Graph theory", "Edge relaxation", "Dynamic Programming"],
        "similar_problems": ["Negative cycle detection", "Currency arbitrage", "Cheapest flights"],
        "related_topics": ["Dijkstra", "Floyd-Warshall", "Dynamic Programming"],
        "practice_problems": ["LeetCode 743: Network Delay Time", "Detect negative cycle", "Currency arbitrage"],
        "pseudocode": "dist[start] = 0\nfor i = 0 to V-2:\n    for each edge (u, v, w):\n        if dist[u] + w < dist[v]:\n            dist[v] = dist[u] + w\n# Check for negative cycles",
    },
    "Floyd-Warshall Algorithm": {
        "main_concept": "All-Pairs Shortest Path",
        "pattern": "Gradually allow intermediate nodes through DP.",
        "prerequisites": ["Graph theory", "Dynamic Programming", "Matrix"],
        "similar_problems": ["Transitive closure", "City network", "Path reconstruction"],
        "related_topics": ["Dijkstra", "Bellman-Ford", "Dynamic Programming"],
        "practice_problems": ["LeetCode 1334: City With Smallest Number of Neighbors", "Detect negative cycles", "Transitive closure"],
        "pseudocode": "for k = 0 to n-1:\n    for i = 0 to n-1:\n        for j = 0 to n-1:\n            dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])",
    },
    "Union-Find": {
        "main_concept": "Disjoint Set Union",
        "pattern": "Group elements into sets with find and union operations.",
        "prerequisites": ["Arrays", "Tree concept", "Path compression"],
        "similar_problems": ["Connected components", "Number of islands II", "Redundant connection"],
        "related_topics": ["Graph connectivity", "Minimum spanning tree", "Kruskal's algorithm"],
        "practice_problems": ["LeetCode 200: Number of Islands", "LeetCode 547: Number of Provinces", "LeetCode 684: Redundant Connection"],
        "pseudocode": "def find(x):\n    if parent[x] != x:\n        parent[x] = find(parent[x])\n    return parent[x]\n\ndef union(x, y):\n    px, py = find(x), find(y)\n    if px != py:\n        parent[px] = py",
    },
    "Trie": {
        "main_concept": "Prefix Tree",
        "pattern": "Store strings in a tree where each node represents a character.",
        "prerequisites": ["Trees", "Recursion", "String operations"],
        "similar_problems": ["Autocomplete", "Spell checker", "Word search II"],
        "related_topics": ["Hash Map", "Suffix Tree", "String algorithms"],
        "practice_problems": ["LeetCode 208: Implement Trie", "LeetCode 212: Word Search II", "LeetCode 336: Palindrome Pairs"],
        "pseudocode": "class TrieNode:\n    children = {}\n    is_end = False\n\ndef insert(word):\n    for char in word:\n        if char not in node.children:\n            node.children[char] = TrieNode()\n        node = node.children[char]\n    node.is_end = True",
    },
    "Bit Manipulation": {
        "main_concept": "Bitwise Operations",
        "pattern": "Use bitwise operators for efficient computation.",
        "prerequisites": ["Binary numbers", "Boolean algebra", "Bitwise operators"],
        "similar_problems": ["Single number", "Power of two", "Counting bits"],
        "related_topics": ["Binary representation", "XOR properties", "Bit masks"],
        "practice_problems": ["LeetCode 136: Single Number", "LeetCode 191: Number of 1 Bits", "LeetCode 338: Counting Bits"],
        "pseudocode": "# XOR: a ^ a = 0, a ^ 0 = a\n# AND: a & (a-1) clears rightmost bit\n# Shift: a << 1 = a * 2, a >> 1 = a / 2",
    },
    "Counting Sort": {
        "main_concept": "Non-comparison Based Sort",
        "pattern": "Count frequencies of each value, then reconstruct sorted array.",
        "prerequisites": ["Arrays", "Integer ranges", "Frequency counting"],
        "similar_problems": ["Radix Sort", "Bucket Sort", "Frequency analysis"],
        "related_topics": ["Sorting algorithms", "Radix sort", "Bucket sort"],
        "practice_problems": ["Sort array with limited range", "Find duplicates", "Frequency sort"],
        "pseudocode": "count = [0] * (max_val + 1)\nfor v in arr: count[v] += 1\nfor i in range(len(count)):\n    while count[i] > 0:\n        arr[pos] = i\n        pos += 1\n        count[i] -= 1",
    },
}


def get_references(algorithm: str) -> dict:
    return REFERENCES.get(algorithm, {
        "main_concept": "General Programming",
        "pattern": "Iterative or conditional logic.",
        "prerequisites": ["Variables", "Loops", "Conditionals"],
        "similar_problems": ["Varies based on code logic"],
        "related_topics": ["Problem Solving", "Debugging", "Code Analysis"],
        "practice_problems": ["Practice with coding platforms like LeetCode, HackerRank"],
        "pseudocode": "N/A",
    })
